<?php

namespace Jgzz\CmsBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Jgzz\DoctrineI18n\Entity\Repository\TranslationRepository;

/**
 * JzcmsContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JzcmsContentI18nRepository extends TranslationRepository
{

}